name: first workflow
on: workflow_dispatch
jobs: 
  first-job:
    runs-on: ubuntu-latest
    steps:
      - name: print first name
        run: echo "amrut"
      - name: print secondname
        run: echo "anubhav"
